import { useState } from 'react';
import { motion } from 'framer-motion';
import { FileText, Download, CheckCircle2, AlertCircle, Loader2, Share2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Level, Flashcard, Concept } from '../../types/gamification';

interface StudyPackGeneratorProps {
  summary: string;
  levels: Level[];
  flashcards: Flashcard[];
  concepts: Concept[];
  topicTitle?: string;
}

export function StudyPackGenerator({ summary, levels, flashcards, concepts, topicTitle }: StudyPackGeneratorProps) {
  const [isGenerating, setIsGenerating] = useState(false);
  const [isSuccess, setIsSuccess] = useState(false);

  const sanitizeForPdf = (text: string) => {
    if (!text) return "";
    // Replace common non-WinAnsi characters with ASCII equivalents
    return text
      .replace(/\u2022/g, "*") // Bullet to star
      .replace(/\u2013/g, "-") // En-dash to hyphen
      .replace(/\u2014/g, "--") // Em-dash to double hyphen
      .replace(/\u2018/g, "'") // Left single quote
      .replace(/\u2019/g, "'") // Right single quote
      .replace(/\u201C/g, '"') // Left double quote
      .replace(/\u201D/g, '"') // Right double quote
      .replace(/[^\x00-\x7F]/g, "") // Strip any other non-ASCII characters that might corrupt the PDF
      .trim();
  };

  const generatePDF = async () => {
    if (!summary || levels.length === 0) return;
    
    setIsGenerating(true);
    setIsSuccess(false);

    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 20;

      // 1. TITLE SECTION
      doc.setFillColor(59, 130, 246); // Primary Color
      doc.rect(0, 0, pageWidth, 40, 'F');
      
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(24);
      doc.setFont("helvetica", "bold");
      doc.text("AI STUDY PACK", margin, 20);
      
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text(`Generated by LearnForge OS - ${new Date().toLocaleDateString()}`, margin, 30);
      doc.text(`Topic: ${sanitizeForPdf(topicTitle || levels[0].title || 'Personalized Study Synthesis')}`, margin, 35);

      let currentY = 55;

      // 2. EXECUTIVE SUMMARY
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(16);
      doc.setFont("helvetica", "bold");
      doc.text("1. Executive Summary", margin, currentY);
      currentY += 10;
      
      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      const splitSummary = doc.splitTextToSize(sanitizeForPdf(summary), pageWidth - (margin * 2));
      doc.text(splitSummary, margin, currentY);
      currentY += (splitSummary.length * 7) + 15;

      // 3. CONCEPT MAP & MIND MAP (TEXT-BASED)
      if (concepts.length > 0) {
        if (currentY > 250) { doc.addPage(); currentY = margin; }
        doc.setFontSize(16);
        doc.setFont("helvetica", "bold");
        doc.text("2. Topological Concept Guide", margin, currentY);
        currentY += 10;

        // Simple Text Mind Map MVP
        doc.setFontSize(10);
        doc.setFont("courier", "bold");
        doc.text("TOPOLOGICAL MAP:", margin, currentY);
        currentY += 7;
        
        concepts.slice(0, 5).forEach((c, i) => {
          doc.setFont("courier", "normal");
          doc.text(`${i === 0 ? 'ROOT' : ' |--'} ${sanitizeForPdf(c.title)}`, margin + 5, currentY);
          currentY += 6;
        });
        currentY += 10;

        autoTable(doc, {
          startY: currentY,
          head: [['Concept', 'Definition', 'Relational Context']],
          body: concepts.map(c => [sanitizeForPdf(c.title), sanitizeForPdf(c.definition), sanitizeForPdf(c.relationship)]),
          theme: 'striped',
          headStyles: { fillColor: [59, 130, 246] },
          margin: { left: margin, right: margin }
        });
        currentY = (doc as any).lastAutoTable.finalY + 20;
      }

      // 4. ASSESSMENT PACK (QUIZ)
      const allQuestions = levels.flatMap(l => l.questions);
      if (allQuestions.length > 0) {
        if (currentY > 230) { doc.addPage(); currentY = margin; }
        doc.setFontSize(16);
        doc.setFont("helvetica", "bold");
        doc.text("3. Active Recall Assessment", margin, currentY);
        currentY += 10;

        allQuestions.forEach((q, i) => {
          if (currentY > 250) { doc.addPage(); currentY = margin; }
          doc.setFontSize(11);
          doc.setFont("helvetica", "bold");
          doc.text(`${i + 1}. ${sanitizeForPdf(q.question)}`, margin, currentY);
          currentY += 7;

          doc.setFont("helvetica", "normal");
          doc.setFontSize(10);
          q.options.forEach((opt, optIdx) => {
            const label = String.fromCharCode(65 + optIdx);
            doc.text(`${label}) ${sanitizeForPdf(opt)}`, margin + 5, currentY);
            currentY += 5;
          });
          
          doc.setTextColor(100, 100, 100);
          doc.setFontSize(9);
          doc.setFont("helvetica", "italic");
          const sanitizedExp = sanitizeForPdf(q.explanation);
          doc.text(`Correct: ${String.fromCharCode(65 + q.correctAnswer)} | ${sanitizedExp}`, margin + 5, currentY, { maxWidth: pageWidth - 50 });
          doc.setTextColor(0, 0, 0);
          currentY += 15;
        });
      }

      // 5. FLASHCARD APPENDIX
      if (flashcards.length > 0) {
        doc.addPage();
        currentY = margin;
        doc.setFontSize(16);
        doc.setFont("helvetica", "bold");
        doc.text("4. Flashcard Appendix (Q&A)", margin, currentY);
        currentY += 10;

        autoTable(doc, {
          startY: currentY,
          head: [['Flashcard Question', 'Pedagogical Answer']],
          body: flashcards.map(f => [sanitizeForPdf(f.question), sanitizeForPdf(f.answer)]),
          theme: 'grid',
          headStyles: { fillColor: [30, 58, 138] },
          margin: { left: margin, right: margin }
        });
      }

      doc.save(`LearnForge_StudyPack_${Date.now()}.pdf`);
      setIsSuccess(true);
      setTimeout(() => setIsSuccess(false), 3000);
    } catch (error) {
      console.error("PDF Generation failed:", error);
    } finally {
      setIsGenerating(false);
    }
  };

  const hasData = summary && levels.length > 0;

  return (
    <div className="p-8 bg-muted/10 rounded-2xl border border-border/40 flex flex-col items-center text-center">
      <div className="w-16 h-16 bg-primary/10 rounded-2xl flex items-center justify-center mb-6 border border-primary/20">
        <FileText className="w-8 h-8 text-primary" />
      </div>
      
      <h3 className="text-2xl font-bold mb-2">A.I. Study Pack Generator</h3>
      <p className="text-muted-foreground max-w-md mb-8">
        Compile your synthesis summary, neural maps, and active recall tests into a professional study guide.
      </p>

      {!hasData ? (
        <div className="p-4 bg-destructive/10 border border-destructive/30 rounded-xl flex items-center gap-3 text-destructive text-sm max-w-sm">
          <AlertCircle className="w-4 h-4" />
          <p>Please upload content and generate a Neural Path before exporting your Study Pack.</p>
        </div>
      ) : (
        <div className="flex flex-col gap-4 w-full max-w-md">
          <div className="grid grid-cols-2 gap-4 mb-2">
            <div className="p-3 bg-card border border-border rounded-xl">
              <p className="text-xl font-bold text-primary">{levels.flatMap(l => l.questions).length}</p>
              <p className="text-[10px] uppercase font-bold text-muted-foreground tracking-widest">Questions</p>
            </div>
            <div className="p-3 bg-card border border-border rounded-xl">
              <p className="text-xl font-bold text-primary">{flashcards.length}</p>
              <p className="text-[10px] uppercase font-bold text-muted-foreground tracking-widest">Flashcards</p>
            </div>
          </div>

          <Button 
            size="lg" 
            onClick={generatePDF} 
            disabled={isGenerating}
            className="w-full bg-primary hover:bg-primary/90 text-primary-foreground font-bold shadow-xl shadow-primary/20 gap-2 h-14 text-lg"
          >
            {isGenerating ? (
              <><Loader2 className="w-5 h-5 animate-spin" /> Compiling Assets...</>
            ) : isSuccess ? (
              <><CheckCircle2 className="w-5 h-5" /> Pack Downloaded!</>
            ) : (
              <><Download className="w-5 h-5" /> Generate Study PDF</>
            )}
          </Button>

          <p className="text-[10px] text-muted-foreground uppercase tracking-widest flex items-center justify-center gap-2">
            <Share2 className="w-3 h-3" /> Securely generated locally
          </p>
        </div>
      )}
    </div>
  );
}
